---
- name: testing filter options
  hosts: "{{database_host | default('testServer')}}"
  remote_user: ec2-user
  become: yes

  vars:
    cheese: ['american', 'cheddar', 'cheddar', 'mozzarella', 'bleu', 'manchego', 'mozzarella', 'brie']
    pizza_toppings: ['mozzarella', 'anchovies', 'pineapple', 'bleu', 'pepperoni', 'mushrooms', 'ham']
  
  tasks:
  - name: quick echo
    shell: echo $PATH
    register: result

  - debug: msg="The play failed"
    when: result|failed

  - debug: msg="The play changed"
    when: result|changed

  - debug: msg="The play succeeded"
    when: result|success

  - debug: msg="The play skipped"
    when: result|skipped

  - debug: msg="{{cheese | unique}}"

  - debug: msg="{{cheese | difference(pizza_toppings)}}"

  - debug: msg="{{cheese | union(pizza_toppings)}}"