---
- name: testing templates
  hosts: testServer
  remote_user: ec2-user
  become: yes
  
  vars:
    listenport: 8888

  tasks:
  - name: insert iptables template
    template: src=iptables.j2 dest=/etc/sysconfig/iptables
    notify: restart iptables

  handlers: 
  - name: restart iptables
    service: name=iptables state=restarted  